<Project>
  <PropertyGroup>
    <Company>FamilyTheater</Company>
    <Authors>FamilyTheater</Authors>
    <Product>FamilyTheater</Product>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <Version>0.1.0</Version>
    <InformationalVersion>0.1.0</InformationalVersion>
    <NeutralLanguage>zh-CN</NeutralLanguage>
  </PropertyGroup>
</Project>
